# Generated by Django 5.2.3 on 2025-06-18 00:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_formacion', models.CharField(choices=[('TECNICO', 'Técnico'), ('TECNOLOGO', 'Tecnólogo'), ('ESPECIALIZACION', 'Especialización Técnica'), ('CURSO_CORTO', 'Curso Corto'), ('COMPLEMENTARIA', 'Formación Complementaria')], max_length=50)),
                ('duracion_horas', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Programa de Formación',
                'verbose_name_plural': 'Programas de Formación',
                'db_table': 'programas',
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin_lectiva', models.DateField(default=django.utils.timezone.now)),
                ('municipio_departamento', models.CharField(max_length=100)),
                ('centro_formacion', models.CharField(max_length=100)),
                ('cupo_aprendices', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('cupo_instructores', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('lugar_realizacion', models.CharField(max_length=100)),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual'), ('MIXTA', 'Mixta')], max_length=20)),
                ('jornada', models.CharField(choices=[('DIURNA', 'Diurna'), ('NOCTURNA', 'Nocturna'), ('MIXTA', 'Mixta'), ('FINES_SEMANA', 'Fines de Semana')], max_length=20)),
                ('estado', models.CharField(choices=[('LECTURA', 'En Lectura'), ('EJECUCION', 'En Ejecución'), ('TERMINADA', 'Terminada'), ('CANCELADA', 'Cancelada')], default='LECTURA', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='asistencia.programa')),
            ],
            options={
                'verbose_name': 'Ficha',
                'verbose_name_plural': 'Fichas',
                'db_table': 'fichas',
            },
        ),
        migrations.CreateModel(
            name='ResultadoAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('horas_asignadas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('trimestre', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_aprendizaje', to='asistencia.programa')),
            ],
            options={
                'verbose_name': 'Resultado de Aprendizaje',
                'verbose_name_plural': 'Resultados de Aprendizaje',
                'db_table': 'resultados_aprendizaje',
            },
        ),
        migrations.CreateModel(
            name='LlamadoAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_llamado', models.DateTimeField(auto_now_add=True)),
                ('fecha_clase', models.DateField(default=django.utils.timezone.now)),
                ('observaciones_generales', models.TextField(blank=True, help_text='Observaciones generales sobre la clase o el llamado de asistencia', null=True)),
                ('duracion_clase', models.PositiveIntegerField(default=120, help_text='Duración de la clase en minutos', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(480)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llamados_asistencia', to='asistencia.ficha')),
                ('instructor', models.ForeignKey(limit_choices_to={'rol__nombre': 'INSTRUCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='llamados_asistencia', to=settings.AUTH_USER_MODEL)),
                ('resultado_aprendizaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llamados_asistencia', to='asistencia.resultadoaprendizaje')),
            ],
            options={
                'verbose_name': 'Llamado de Asistencia',
                'verbose_name_plural': 'Llamados de Asistencia',
                'db_table': 'llamados_asistencia',
                'unique_together': {('instructor', 'resultado_aprendizaje', 'ficha', 'fecha_clase')},
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_matricula', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('RETIRADO', 'Retirado'), ('APLAZADO', 'Aplazado'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20)),
                ('foto_perfil', models.ImageField(blank=True, help_text='Foto del aprendiz para identificación visual en asistencia', null=True, upload_to='fotos_perfil/')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprendiz', models.ForeignKey(limit_choices_to={'rol': 'APRENDIZ'}, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='asistencia.ficha')),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'Matriculas',
                'db_table': 'matriculas',
                'unique_together': {('aprendiz', 'ficha')},
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('JUSTIFICADO', 'Justificado'), ('TARDE', 'Llegó Tarde')], default='PRESENTE', max_length=15)),
                ('hora_registro', models.TimeField(auto_now_add=True, help_text='Hora en que se registró la asistencia')),
                ('minutos_tarde', models.PositiveIntegerField(default=0, help_text='Minutos de retraso (solo si llegó tarde)', validators=[django.core.validators.MaxValueValidator(180)])),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones específicas sobre la asistencia del aprendiz', max_length=500, null=True)),
                ('se_retiro_antes', models.BooleanField(default=False, help_text='Indica si el aprendiz se retiró antes de finalizar la clase')),
                ('hora_retiro', models.TimeField(blank=True, help_text='Hora de retiro (si se retiró antes)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprendiz', models.ForeignKey(limit_choices_to={'rol': 'APRENDIZ'}, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL)),
                ('llamado_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='asistencia.llamadoasistencia')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'db_table': 'registros_asistencia',
                'unique_together': {('llamado_asistencia', 'aprendiz')},
            },
        ),
        migrations.CreateModel(
            name='EstadisticaAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_clases', models.PositiveIntegerField(default=0)),
                ('clases_presentes', models.PositiveIntegerField(default=0)),
                ('clases_ausentes', models.PositiveIntegerField(default=0)),
                ('clases_justificadas', models.PositiveIntegerField(default=0)),
                ('clases_tarde', models.PositiveIntegerField(default=0)),
                ('porcentaje_asistencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('aprendiz', models.ForeignKey(limit_choices_to={'rol': 'APRENDIZ'}, on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_asistencia', to=settings.AUTH_USER_MODEL)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_asistencia', to='asistencia.ficha')),
                ('resultado_aprendizaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_asistencia', to='asistencia.resultadoaprendizaje')),
            ],
            options={
                'verbose_name': 'Estadística de Asistencia',
                'verbose_name_plural': 'Estadísticas de Asistencia',
                'db_table': 'estadisticas_asistencia',
                'unique_together': {('aprendiz', 'resultado_aprendizaje', 'ficha')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(limit_choices_to={'rol': 'INSTRUCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to=settings.AUTH_USER_MODEL)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='asistencia.ficha')),
                ('resultado_aprendizaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='asistencia.resultadoaprendizaje')),
            ],
            options={
                'verbose_name': 'Asignación de Instructor',
                'verbose_name_plural': 'Asignaciones de Instructores',
                'db_table': 'asignaciones_instructor',
                'unique_together': {('instructor', 'resultado_aprendizaje', 'ficha')},
            },
        ),
    ]
