# Generated by Django 5.2.3 on 2025-06-18 01:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matricula',
            options={'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.AlterField(
            model_name='asignacioninstructor',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'rol__nombre': 'INSTRUCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estadisticaasistencia',
            name='aprendiz',
            field=models.ForeignKey(limit_choices_to={'rol__nombre': 'APRENDIZ'}, on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_asistencia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='cupo_aprendices',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='cupo_instructores',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='fecha_fin_lectiva',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='aprendiz',
            field=models.ForeignKey(limit_choices_to={'rol__nombre': 'APRENDIZ'}, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='aprendiz',
            field=models.ForeignKey(limit_choices_to={'rol__nombre': 'APRENDIZ'}, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resultadoaprendizaje',
            name='horas_asignadas',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddIndex(
            model_name='asignacioninstructor',
            index=models.Index(fields=['instructor', 'ficha'], name='asignacione_instruc_dc6dba_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacioninstructor',
            index=models.Index(fields=['fecha_inicio'], name='asignacione_fecha_i_3db7ac_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacioninstructor',
            index=models.Index(fields=['activo'], name='asignacione_activo_710c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='estadisticaasistencia',
            index=models.Index(fields=['aprendiz', 'ficha'], name='estadistica_aprendi_15c371_idx'),
        ),
        migrations.AddIndex(
            model_name='estadisticaasistencia',
            index=models.Index(fields=['porcentaje_asistencia'], name='estadistica_porcent_65c341_idx'),
        ),
        migrations.AddIndex(
            model_name='ficha',
            index=models.Index(fields=['numero'], name='fichas_numero_8ea8d4_idx'),
        ),
        migrations.AddIndex(
            model_name='ficha',
            index=models.Index(fields=['estado'], name='fichas_estado_840bd2_idx'),
        ),
        migrations.AddIndex(
            model_name='ficha',
            index=models.Index(fields=['fecha_inicio'], name='fichas_fecha_i_378dee_idx'),
        ),
        migrations.AddIndex(
            model_name='ficha',
            index=models.Index(fields=['activo'], name='fichas_activo_d6b288_idx'),
        ),
        migrations.AddIndex(
            model_name='llamadoasistencia',
            index=models.Index(fields=['fecha_clase'], name='llamados_as_fecha_c_7ca46d_idx'),
        ),
        migrations.AddIndex(
            model_name='llamadoasistencia',
            index=models.Index(fields=['instructor', 'fecha_clase'], name='llamados_as_instruc_76bdaf_idx'),
        ),
        migrations.AddIndex(
            model_name='llamadoasistencia',
            index=models.Index(fields=['ficha', 'fecha_clase'], name='llamados_as_ficha_i_b695d7_idx'),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['estado'], name='matriculas_estado_75a764_idx'),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['fecha_matricula'], name='matriculas_fecha_m_16c335_idx'),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['activo'], name='matriculas_activo_e5a0e0_idx'),
        ),
        migrations.AddIndex(
            model_name='programa',
            index=models.Index(fields=['codigo'], name='programas_codigo_32eb8b_idx'),
        ),
        migrations.AddIndex(
            model_name='programa',
            index=models.Index(fields=['activo'], name='programas_activo_2cb0e7_idx'),
        ),
        migrations.AddIndex(
            model_name='registroasistencia',
            index=models.Index(fields=['estado'], name='registros_a_estado_774ffb_idx'),
        ),
        migrations.AddIndex(
            model_name='registroasistencia',
            index=models.Index(fields=['aprendiz', 'llamado_asistencia'], name='registros_a_aprendi_0ff52a_idx'),
        ),
        migrations.AddIndex(
            model_name='resultadoaprendizaje',
            index=models.Index(fields=['codigo'], name='resultados__codigo_bac41d_idx'),
        ),
        migrations.AddIndex(
            model_name='resultadoaprendizaje',
            index=models.Index(fields=['programa'], name='resultados__program_0646b9_idx'),
        ),
        migrations.AddIndex(
            model_name='resultadoaprendizaje',
            index=models.Index(fields=['trimestre'], name='resultados__trimest_e0e78b_idx'),
        ),
        migrations.AddIndex(
            model_name='resultadoaprendizaje',
            index=models.Index(fields=['activo'], name='resultados__activo_81e09e_idx'),
        ),
    ]
