# Generated by Django 5.2.3 on 2025-06-18 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_alter_matricula_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='aprendiz',
            field=models.ForeignKey(limit_choices_to={'rol_nombre': 'APRENDIZ'}, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL),
        ),
    ]
