# Generated by Django 5.2.3 on 2025-06-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_alter_matricula_aprendiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamadoasistencia',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el llamado de asistencia está activo'),
        ),
    ]
