# Generated by Django 5.2.3 on 2025-06-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_llamadoasistencia_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='estado',
            field=models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('JUSTIFICADO', 'Justificado'), ('TARDE', 'Llegó Tarde')], default='PENDIENTE', max_length=15),
        ),
    ]
