# Generated by Django 5.2.3 on 2025-06-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0008_alter_registroasistencia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='estado',
            field=models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('JUSTIFICADO', 'Justificado'), ('TARDE', 'Llegó Tarde')], default='AUSENTE', max_length=15),
        ),
    ]
