# Generated by Django 5.2.3 on 2025-06-20 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0009_alter_registroasistencia_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaPorFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencia_ficha', to='asistencia.ficha')),
            ],
            options={
                'verbose_name': 'Asistencia por Ficha',
                'verbose_name_plural': 'Asistencias por Ficha',
                'db_table': 'asistencia_por_ficha',
                'indexes': [models.Index(fields=['ficha'], name='asistencia__ficha_i_233143_idx'), models.Index(fields=['fecha_inicio'], name='asistencia__fecha_i_b71eca_idx'), models.Index(fields=['fecha_fin'], name='asistencia__fecha_f_5e4388_idx')],
            },
        ),
    ]
