# Generated by Django 5.2.3 on 2025-06-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0010_asistenciaporficha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llamadoasistencia',
            name='activo',
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='estado',
            field=models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('JUSTIFICADO', 'Justificado'), ('TARDE', 'Llegó Tarde')], default='PRESENTE', max_length=15),
        ),
        migrations.DeleteModel(
            name='AsistenciaPorFicha',
        ),
    ]
