# Generated by Django 4.1.13 on 2025-06-23 05:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0011_remove_llamadoasistencia_activo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitacionComite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_citacion', models.CharField(editable=False, max_length=20, unique=True)),
                ('motivo', models.CharField(choices=[('BAJO_RENDIMIENTO', 'Bajo Rendimiento Académico'), ('INASISTENCIA', 'Inasistencia Recurrente'), ('COMPORTAMIENTO', 'Problemas de Comportamiento'), ('INCUMPLIMIENTO', 'Incumplimiento de Normas'), ('SOLICITUD_APRENDIZ', 'Solicitud del Aprendiz'), ('OTRO', 'Otro Motivo')], max_length=30)),
                ('motivo_detallado', models.TextField(help_text='Descripción detallada del motivo de la citación')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('NOTIFICADA', 'Notificada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_citacion', models.DateTimeField(help_text='Fecha y hora programada para la citación')),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_realizacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones_instructor', models.TextField(blank=True, help_text='Observaciones adicionales del instructor', null=True)),
                ('observaciones_comite', models.TextField(blank=True, help_text='Observaciones del comité después de la citación', null=True)),
                ('requiere_seguimiento', models.BooleanField(default=False, help_text='Indica si la citación requiere seguimiento posterior')),
                ('fecha_seguimiento', models.DateField(blank=True, help_text='Fecha programada para el seguimiento', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprendiz', models.ForeignKey(limit_choices_to={'rol__nombre': 'APRENDIZ'}, on_delete=django.db.models.deletion.CASCADE, related_name='citaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citaciones', to='asistencia.ficha')),
                ('instructor_citante', models.ForeignKey(limit_choices_to={'rol__nombre': 'INSTRUCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='citaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('resultado_aprendizaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citaciones', to='asistencia.resultadoaprendizaje')),
            ],
            options={
                'verbose_name': 'Citación a Comité',
                'verbose_name_plural': 'Citaciones a Comité',
                'db_table': 'citaciones_comite',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoCitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_seguimiento', models.CharField(choices=[('ACADEMICO', 'Seguimiento Académico'), ('COMPORTAMENTAL', 'Seguimiento Comportamental'), ('ASISTENCIA', 'Seguimiento de Asistencia'), ('INTEGRAL', 'Seguimiento Integral')], max_length=20)),
                ('fecha_seguimiento', models.DateField()),
                ('observaciones', models.TextField()),
                ('resultado', models.CharField(choices=[('MEJORA', 'Mejora Evidenciada'), ('ESTABLE', 'Situación Estable'), ('DETERIORO', 'Deterioro de la Situación'), ('SIN_CAMBIOS', 'Sin Cambios Significativos')], max_length=15)),
                ('acciones_tomadas', models.TextField(blank=True, help_text='Acciones específicas tomadas durante el seguimiento', null=True)),
                ('requiere_nuevo_seguimiento', models.BooleanField(default=False)),
                ('fecha_proximo_seguimiento', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='comite.citacioncomite')),
                ('instructor_seguimiento', models.ForeignKey(limit_choices_to={'rol__nombre': 'INSTRUCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento de Citación',
                'verbose_name_plural': 'Seguimientos de Citaciones',
                'db_table': 'seguimientos_citaciones',
                'ordering': ['-fecha_seguimiento'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoAdjuntoCitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='citaciones/adjuntos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])])),
                ('nombre_original', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('citacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='comite.citacioncomite')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_citaciones_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo Adjunto de Citación',
                'verbose_name_plural': 'Archivos Adjuntos de Citaciones',
                'db_table': 'archivos_adjuntos_citaciones',
            },
        ),
        migrations.AddIndex(
            model_name='citacioncomite',
            index=models.Index(fields=['aprendiz', 'estado'], name='citaciones__aprendi_ae1c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='citacioncomite',
            index=models.Index(fields=['instructor_citante'], name='citaciones__instruc_8da46b_idx'),
        ),
        migrations.AddIndex(
            model_name='citacioncomite',
            index=models.Index(fields=['fecha_citacion'], name='citaciones__fecha_c_5329ae_idx'),
        ),
        migrations.AddIndex(
            model_name='citacioncomite',
            index=models.Index(fields=['estado'], name='citaciones__estado_db1320_idx'),
        ),
        migrations.AddIndex(
            model_name='citacioncomite',
            index=models.Index(fields=['motivo'], name='citaciones__motivo_fc63a3_idx'),
        ),
        migrations.AddIndex(
            model_name='citacioncomite',
            index=models.Index(fields=['prioridad'], name='citaciones__priorid_c63c1a_idx'),
        ),
    ]
