# Generated by Django 4.1.13 on 2025-06-23 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientocitacion',
            name='instructor_seguimiento',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__nombre': 'INSTRUCTOR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_realizados', to=settings.AUTH_USER_MODEL),
        ),
    ]
