# Generated by Django 4.1.13 on 2025-06-23 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('NUEVA_ACTIVIDAD', 'Nueva Actividad'), ('ACTIVIDAD_VALORADA', 'Actividad Valorada'), ('CITACION_COMITE', 'Citación a Comité'), ('ALTA_INASISTENCIA', 'Alta Inasistencia'), ('BAJO_RENDIMIENTO', 'Bajo Rendimiento'), ('RECORDATORIO', 'Recordatorio'), ('SISTEMA', 'Sistema')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Notificación',
                'verbose_name_plural': 'Tipos de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('datos_extra', models.JSONField(blank=True, default=dict)),
                ('enviada_push', models.BooleanField(default=False)),
                ('enviada_email', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificaciones.tiponotificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_envio', models.CharField(choices=[('PUSH', 'Notificación Push'), ('EMAIL', 'Correo Electrónico'), ('SMS', 'Mensaje de Texto')], max_length=20)),
                ('estado', models.CharField(choices=[('ENVIADO', 'Enviado'), ('FALLIDO', 'Fallido'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('mensaje_error', models.TextField(blank=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='notificaciones.notificacion')),
            ],
            options={
                'verbose_name': 'Historial de Notificación',
                'verbose_name_plural': 'Historial de Notificaciones',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificaciones_push', models.BooleanField(default=True)),
                ('notificaciones_email', models.BooleanField(default=True)),
                ('nueva_actividad', models.BooleanField(default=True)),
                ('actividad_valorada', models.BooleanField(default=True)),
                ('citacion_comite', models.BooleanField(default=True)),
                ('alta_inasistencia', models.BooleanField(default=True)),
                ('bajo_rendimiento', models.BooleanField(default=True)),
                ('recordatorios', models.BooleanField(default=True)),
                ('hora_inicio', models.TimeField(default='07:00')),
                ('hora_fin', models.TimeField(default='22:00')),
                ('dias_activos', models.JSONField(default=list, help_text='Lista de días de la semana activos (0=Lunes, 6=Domingo)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Notificación',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
            },
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', 'leida'], name='notificacio_usuario_2c9179_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['tipo', 'fecha_creacion'], name='notificacio_tipo_id_3ca940_idx'),
        ),
    ]
