# Generated by Django 5.2.3 on 2025-06-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='token_recuperacion',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
