# Generated by Django 5.2.3 on 2025-06-21 02:43

import apps.actividades.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0011_remove_llamadoasistencia_activo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_entrega', models.DateTimeField()),
                ('fecha_limite', models.DateTimeField(blank=True, help_text='Fecha límite para entrega tardía', null=True)),
                ('modalidad', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GRUPAL', 'Grupal'), ('MIXTA', 'Mixta')], default='INDIVIDUAL', max_length=20)),
                ('numero_integrantes_grupo', models.PositiveIntegerField(default=1, help_text='Solo aplica para actividades grupales', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('permite_entrega_tardia', models.BooleanField(default=True)),
                ('penalizacion_tardanza', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de penalización por entrega tardía', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)])),
                ('criterios_evaluacion', models.TextField(blank=True, help_text='Criterios de evaluación y rúbricas', null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADA', 'Publicada'), ('EN_PROGRESO', 'En Progreso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('es_obligatoria', models.BooleanField(default=True)),
                ('visible_para_aprendices', models.BooleanField(default=True)),
                ('requiere_archivo', models.BooleanField(default=False)),
                ('observaciones_instructor', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='asistencia.ficha')),
                ('instructor', models.ForeignKey(limit_choices_to={'rol__nombre': 'INSTRUCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL)),
                ('resultado_aprendizaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='asistencia.resultadoaprendizaje')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividades',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EntregaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(blank=True, help_text='Texto de la entrega', null=True)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENTREGADA', 'Entregada'), ('REVISADA', 'Revisada'), ('CALIFICADA', 'Calificada'), ('DEVUELTA', 'Devuelta para Corrección')], default='BORRADOR', max_length=20)),
                ('es_entrega_tardia', models.BooleanField(default=False)),
                ('observaciones_aprendiz', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='actividades.actividad')),
                ('aprendiz', models.ForeignKey(limit_choices_to={'rol__nombre': 'APRENDIZ'}, on_delete=django.db.models.deletion.CASCADE, related_name='entregas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrega de Actividad',
                'verbose_name_plural': 'Entregas de Actividades',
                'db_table': 'entregas_actividad',
                'ordering': ['-fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='CalificacionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fortalezas', models.TextField(blank=True, null=True)),
                ('aspectos_mejorar', models.TextField(blank=True, null=True)),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('requiere_correccion', models.BooleanField(default=False)),
                ('aprobada', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(limit_choices_to={'rol__nombre': 'INSTRUCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_dadas', to=settings.AUTH_USER_MODEL)),
                ('entrega', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='actividades.entregaactividad')),
            ],
            options={
                'verbose_name': 'Calificación de Actividad',
                'verbose_name_plural': 'Calificaciones de Actividades',
                'db_table': 'calificaciones_actividad',
            },
        ),
        migrations.CreateModel(
            name='ArchivoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to=apps.actividades.models.upload_entrega_actividad)),
                ('tamaño_archivo', models.PositiveIntegerField(default=0)),
                ('tipo_archivo', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='actividades.entregaactividad')),
            ],
            options={
                'verbose_name': 'Archivo de Entrega',
                'verbose_name_plural': 'Archivos de Entregas',
                'db_table': 'archivos_entrega',
            },
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('CONSULTA', 'Consulta'), ('TRABAJO', 'Trabajo'), ('PROYECTO', 'Proyecto'), ('VALORACION', 'Valoración'), ('TALLER', 'Taller'), ('EXPOSICION', 'Exposición'), ('PRACTICA', 'Práctica'), ('EXAMEN', 'Examen'), ('QUIZ', 'Quiz'), ('INVESTIGACION', 'Investigación')], max_length=50, unique=True, verbose_name='Tipo de Actividad')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Tipo de Actividad',
                'verbose_name_plural': 'Tipos de Actividades',
                'db_table': 'tipo_actividad',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='tipo_activi_nombre_79de18_idx'), models.Index(fields=['activo'], name='tipo_activi_activo_6b389f_idx')],
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='actividades.tipoactividad'),
        ),
        migrations.CreateModel(
            name='ArchivoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('archivo', models.FileField(upload_to=apps.actividades.models.upload_archivo_actividad, verbose_name='Archivo')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_obligatorio', models.BooleanField(default=False, help_text='Si es obligatorio para realizar la actividad')),
                ('tamaño_archivo', models.PositiveIntegerField(default=0, help_text='Tamaño en bytes')),
                ('tipo_archivo', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='actividades.actividad')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo de Actividad',
                'verbose_name_plural': 'Archivos de Actividades',
                'db_table': 'archivos_actividad',
                'indexes': [models.Index(fields=['actividad'], name='archivos_ac_activid_562d4d_idx'), models.Index(fields=['es_obligatorio'], name='archivos_ac_es_obli_72ee65_idx')],
            },
        ),
        migrations.CreateModel(
            name='AsignacionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_obligatoria', models.BooleanField(default=True, verbose_name='Es Obligatoria')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.actividad')),
                ('aprendiz', models.ForeignKey(limit_choices_to={'rol__nombre': 'APRENDIZ'}, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Actividad',
                'verbose_name_plural': 'Asignaciones de Actividades',
                'db_table': 'asignaciones_actividad',
                'indexes': [models.Index(fields=['actividad', 'aprendiz'], name='asignacione_activid_6da421_idx'), models.Index(fields=['fecha_asignacion'], name='asignacione_fecha_a_ef46a1_idx')],
                'unique_together': {('actividad', 'aprendiz')},
            },
        ),
        migrations.AddIndex(
            model_name='entregaactividad',
            index=models.Index(fields=['actividad', 'aprendiz'], name='entregas_ac_activid_8942f7_idx'),
        ),
        migrations.AddIndex(
            model_name='entregaactividad',
            index=models.Index(fields=['fecha_entrega'], name='entregas_ac_fecha_e_219d04_idx'),
        ),
        migrations.AddIndex(
            model_name='entregaactividad',
            index=models.Index(fields=['estado'], name='entregas_ac_estado_7e0cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='entregaactividad',
            index=models.Index(fields=['es_entrega_tardia'], name='entregas_ac_es_entr_704ea2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entregaactividad',
            unique_together={('actividad', 'aprendiz')},
        ),
        migrations.AddIndex(
            model_name='calificacionactividad',
            index=models.Index(fields=['instructor'], name='calificacio_instruc_fe915f_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacionactividad',
            index=models.Index(fields=['fecha_calificacion'], name='calificacio_fecha_c_944fbc_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacionactividad',
            index=models.Index(fields=['aprobada'], name='calificacio_aprobad_80fc55_idx'),
        ),
        migrations.AddIndex(
            model_name='archivoentrega',
            index=models.Index(fields=['entrega'], name='archivos_en_entrega_9ddd18_idx'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['instructor', 'ficha'], name='actividades_instruc_583802_idx'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['fecha_entrega'], name='actividades_fecha_e_a041e9_idx'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['estado'], name='actividades_estado_398723_idx'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['resultado_aprendizaje'], name='actividades_resulta_36ca88_idx'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['visible_para_aprendices'], name='actividades_visible_e25235_idx'),
        ),
    ]
